# Generated by Django 4.0 on 2021-12-29 09:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image_postview_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django.jpeg', upload_to=blog.models.user_directory_path),
        ),
    ]
